### ISSUE TITLE
Set-Cookie/SameSite warning 

### ISSUE THREAD

**Issue by evan70** [jbroadway/wires#4]
How can I set SameSite cookie fo nginx ?

Cookie “elefant_user” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Thank You

**Comment by jbroadway** [comment]
I believe the `setcookie()` function only got support for setting the samesite attribute in PHP 7.3, so upgrading PHP should fix it (it should then automatically set it to "samesite=Lax"). I did find a couple other places where cookies weren't getting assigned a samesite value, so I've fixed that up for those too now.

**Comment by evan70** [comment]
Thank You > i was dockered at php 7.1 > but 
now im 7.3 >
http://projects.docksal/wires/demos/
![Screenshot from 2020-07-18 00-08-34](https://user-images.githubusercontent.com/67433/87834580-136ad800-c88b-11ea-8fe5-36e07be85d72.png)

**Comment by evan70** [comment]
no warnings on debugger >
but >
![Screenshot from 2020-07-18 00-12-56](https://user-images.githubusercontent.com/67433/87834803-9b50e200-c88b-11ea-8654-d962a511df0b.png)

**Comment by evan70** [comment]
![Screenshot from 2020-07-18 00-27-20](https://user-images.githubusercontent.com/67433/87835483-8c6b2f00-c88d-11ea-887a-4992016746fe.png)

**Comment by evan70** [comment]
yeaah > it's work like Charm at  php7.4 ;)
srry for Bumping :+1:

**Comment by evan70** [comment]
![Screenshot from 2020-07-18 00-55-07](https://user-images.githubusercontent.com/67433/87836703-5c258f80-c891-11ea-8d32-559b3cb393e2.png)

**Comment by jbroadway** [comment]
Ah yes, it looks like I added typed properties which I didn't even think about at the time but made it PHP 7.4+ only. Glad you were able to upgrade and get it working.

**Comment by evan70** [comment]
yeah, thank for docker i already know > php 7.4 even exist :)
Thnk 4 rocket responses > Have a Nice days ...
